(() => {
  let data = BAP.getData();
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const escapeHtml = str => String(str ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const categories={barber:'حلاقة داخل المحل',home:'حلاقة منزلية',massage:'مساج منزلي'};
  const toast = msg => { const el=document.createElement('div');el.textContent=msg;Object.assign(el.style,{position:'fixed',left:'24px',bottom:'24px',background:'#f2d99e',color:'#18130a',padding:'11px 15px',borderRadius:'12px',zIndex:999,fontWeight:'700'});document.body.appendChild(el);setTimeout(()=>el.remove(),1700); };

  function go(page){ $$('.page').forEach(x=>x.classList.remove('active')); $$('.side-link[data-page]').forEach(x=>x.classList.remove('active')); $('#page-'+page).classList.add('active'); const link=$(`.side-link[data-page="${page}"]`); if(link) link.classList.add('active'); $('#topTitle').textContent = link ? link.textContent.trim() : 'لوحة التحكم'; $('#sidebar').classList.remove('show'); if(page==='bookings'||page==='dashboard') renderBookings(); }
  document.addEventListener('click',e=>{ const p=e.target.closest('[data-page]');const g=e.target.closest('[data-go]');if(p)go(p.dataset.page);if(g)go(g.dataset.go); });
  $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('show');

  function bookingTable(items, compact=false){ if(!items.length)return '<div class="empty-admin">لا توجد حجوزات بعد. جرّب تسجيل حجز من الواجهة العامة.</div>'; return `<div class="table-wrap"><table><thead><tr><th>الطلب</th><th>العميل</th><th>الخدمة</th><th>الموعد</th><th>الحالة</th>${compact?'':'<th>الإجراء</th>'}</tr></thead><tbody>${items.map(b=>`<tr><td>${escapeHtml(b.id)}</td><td><b>${escapeHtml(b.name)}</b><br><span class="muted">${escapeHtml(b.phone)}</span></td><td>${escapeHtml(b.serviceName)}${b.location?`<br><span class="muted">${escapeHtml(b.location)}</span>`:''}</td><td>${escapeHtml(b.date)}<br><span class="muted">${escapeHtml(b.time)}</span></td><td><span class="badge ${b.status==='جديد'?'new':'ok'}">${escapeHtml(b.status)}</span></td>${compact?'':`<td><div class="table-actions"><button class="icon-btn" data-status="${b.id}" title="تأكيد">✓</button><button class="icon-btn" data-delete-booking="${b.id}" title="حذف">×</button></div></td>`}</tr>`).join('')}</tbody></table></div>`; }
  function renderBookings(){ const bookings=BAP.getBookings(); $('#kpiBookings').textContent=bookings.length; $('#kpiNew').textContent=bookings.filter(b=>b.status==='جديد').length; $('#kpiServices').textContent=data.services.filter(s=>s.active).length; $('#kpiProducts').textContent=(data.products||[]).length; $('#latestBookings').innerHTML=bookingTable(bookings.slice(0,5),true); $('#bookingsTable').innerHTML=bookingTable(bookings); $('#schoolStatus').innerHTML=data.settings.schoolTransportEnabled?'<b>✓</b> التوصيل المدرسي ظاهر':'<b>—</b> التوصيل المدرسي مخفي'; }
  document.addEventListener('click',e=>{const id=e.target.dataset.status;if(id){const arr=BAP.getBookings();const b=arr.find(x=>x.id===id);if(b)b.status='مؤكد';BAP.setBookings(arr);renderBookings();toast('تم تأكيد الحجز');}const del=e.target.dataset.deleteBooking;if(del){BAP.setBookings(BAP.getBookings().filter(x=>x.id!==del));renderBookings();}});
  $('#clearBookings').onclick=()=>{BAP.setBookings([]);renderBookings();toast('تم مسح الحجوزات التجريبية');};

  function renderServices(){ $('#servicesEditor').innerHTML=data.services.map((s,i)=>`<div class="service-editor-card" data-service-row="${i}"><div class="service-editor-head"><div><div class="name">${escapeHtml(s.name)}</div><div class="muted" style="font-size:11px">${categories[s.category]||s.category}</div></div><label class="toggle-row" style="padding:7px 9px"><span style="font-size:11px">ظاهر</span><input class="toggle" data-key="active" type="checkbox" ${s.active?'checked':''}></label></div><div class="settings-form"><div class="field"><label>اسم الخدمة</label><input data-key="name" value="${escapeHtml(s.name)}"></div><div class="field"><label>السعر</label><input data-key="priceMin" type="number" min="0" value="${s.priceMin}"></div><div class="field"><label>المدة</label><input data-key="duration" value="${escapeHtml(s.duration)}"></div><div class="field full"><label>الوصف</label><textarea data-key="description" rows="3">${escapeHtml(s.description||'')}</textarea></div></div></div>`).join(''); }
  $('#saveServices').onclick=()=>{ $$('[data-service-row]').forEach(row=>{const s=data.services[+row.dataset.serviceRow];s.name=row.querySelector('[data-key="name"]').value;s.priceMin=+row.querySelector('[data-key="priceMin"]').value;s.priceMax=s.priceMin;s.duration=row.querySelector('[data-key="duration"]').value;s.description=row.querySelector('[data-key="description"]').value;s.active=row.querySelector('[data-key="active"]').checked;});BAP.setData(data);renderBookings();toast('تم حفظ الخدمات ومحتواها'); };

  function renderPackages(){ $('#packagesEditor').innerHTML=(data.packages||[]).map((p,i)=>`<div class="service-editor-card" data-package-row="${i}"><div class="service-editor-head"><div><div class="name">${escapeHtml(p.name)}</div><div class="muted" style="font-size:11px">${escapeHtml(p.visits)}</div></div><label class="toggle-row" style="padding:7px 9px"><span style="font-size:11px">ظاهر</span><input class="toggle" data-key="active" type="checkbox" ${p.active?'checked':''}></label></div><div class="settings-form"><div class="field"><label>اسم الباقة</label><input data-key="name" value="${escapeHtml(p.name)}"></div><div class="field"><label>السعر</label><input data-key="price" type="number" min="0" value="${p.price}"></div><div class="field"><label>المدة</label><input data-key="period" value="${escapeHtml(p.period)}"></div><div class="field"><label>الزيارات</label><input data-key="visits" value="${escapeHtml(p.visits||'')}"></div><div class="field full"><label>ما الذي تتضمنه؟</label><input data-key="includes" value="${escapeHtml(p.includes||'')}"></div></div></div>`).join(''); }
  $('#savePackages').onclick=()=>{ $$('[data-package-row]').forEach(row=>{const p=data.packages[+row.dataset.packageRow];p.name=row.querySelector('[data-key="name"]').value;p.price=+row.querySelector('[data-key="price"]').value;p.period=row.querySelector('[data-key="period"]').value;p.visits=row.querySelector('[data-key="visits"]').value;p.includes=row.querySelector('[data-key="includes"]').value;p.active=row.querySelector('[data-key="active"]').checked;});BAP.setData(data);toast('تم حفظ الباقات ومحتواها'); };

  function renderProducts(){ const products=data.products||[]; if(!products.length){$('#productsEditor').innerHTML='<div class="empty-admin">لا توجد منتجات في المصدر. استخدم «إضافة منتج» عند توفر أسماء وأسعار منتجات العناية الفعلية.</div>';return;} $('#productsEditor').innerHTML=`<div class="editor-list">${products.map((p,i)=>`<div class="editor-row" data-product-row="${i}"><input class="name" data-key="name" value="${escapeHtml(p.name)}"><input data-key="price" type="number" min="0" value="${p.price||0}"><input data-key="description" value="${escapeHtml(p.description||'')}"><button class="icon-btn" data-delete-product="${i}">×</button></div>`).join('')}</div><div style="margin-top:14px"><button class="btn btn-primary" id="saveProductsInline">حفظ المنتجات</button></div>`; $('#saveProductsInline').onclick=saveProducts; }
  function saveProducts(){ $$('[data-product-row]').forEach(row=>{const p=data.products[+row.dataset.productRow];p.name=row.querySelector('[data-key="name"]').value;p.price=+row.querySelector('[data-key="price"]').value;p.description=row.querySelector('[data-key="description"]').value;p.active=true;});BAP.setData(data);renderBookings();toast('تم حفظ المنتجات'); }
  $('#addProduct').onclick=()=>{data.products=data.products||[];data.products.push({id:'product-'+Date.now(),name:'منتج جديد',price:0,description:'',active:true});renderProducts();};
  document.addEventListener('click',e=>{if(e.target.dataset.deleteProduct!==undefined){data.products.splice(+e.target.dataset.deleteProduct,1);BAP.setData(data);renderProducts();renderBookings();}});

  function loadContent(){ $('#brandNameInput').value=data.brand.name;$('#taglineInput').value=data.brand.tagline;$('#cityInput').value=data.brand.city;$('#districtInput').value=data.brand.district;$('#addressInput').value=data.brand.address||'';$('#phoneInput').value=data.brand.phone||'';$('#whatsappInput').value=data.brand.whatsapp||'';$('#hoursInput').value=data.brand.hours||'';$('#heroTitleInput').value=data.brand.heroTitle;$('#heroTextInput').value=data.brand.heroText; }
  $('#saveContent').onclick=()=>{data.brand.name=$('#brandNameInput').value;data.brand.tagline=$('#taglineInput').value;data.brand.city=$('#cityInput').value;data.brand.district=$('#districtInput').value;data.brand.address=$('#addressInput').value;data.brand.phone=$('#phoneInput').value;data.brand.whatsapp=$('#whatsappInput').value;data.brand.hours=$('#hoursInput').value;data.brand.heroTitle=$('#heroTitleInput').value;data.brand.heroText=$('#heroTextInput').value;BAP.setData(data);toast('تم حفظ محتوى الموقع');};

  function renderFaqs(){ const items=data.faqs||[]; $('#faqsEditor').innerHTML=items.map((f,i)=>`<div class="faq-edit-row" data-faq-row="${i}"><div class="field"><label>السؤال</label><input data-key="q" value="${escapeHtml(f.q)}"></div><div class="field"><label>الإجابة</label><textarea data-key="a" rows="3">${escapeHtml(f.a)}</textarea></div><button class="icon-btn faq-delete" data-delete-faq="${i}" title="حذف">×</button></div>`).join('') || '<div class="empty-admin">لا توجد أسئلة بعد.</div>'; }
  $('#addFaq').onclick=()=>{data.faqs=data.faqs||[];data.faqs.push({q:'سؤال جديد',a:'اكتب الإجابة هنا.'});renderFaqs();};
  $('#saveFaqs').onclick=()=>{$$('[data-faq-row]').forEach(row=>{const f=data.faqs[+row.dataset.faqRow];f.q=row.querySelector('[data-key="q"]').value;f.a=row.querySelector('[data-key="a"]').value;});BAP.setData(data);toast('تم حفظ الأسئلة الشائعة');};
  document.addEventListener('click',e=>{if(e.target.dataset.deleteFaq!==undefined){data.faqs.splice(+e.target.dataset.deleteFaq,1);BAP.setData(data);renderFaqs();toast('تم حذف السؤال');}});
  function loadSettings(){ $('#homeDistrictInput').value=data.settings.homeServiceDistrict;$('#currencyInput').value=data.settings.currency;$('#paymentToggle').checked=!!data.settings.onlinePaymentEnabled;$('#schoolToggle').checked=!!data.settings.schoolTransportEnabled; }
  $('#saveSettings').onclick=()=>{data.settings.homeServiceDistrict=$('#homeDistrictInput').value;data.settings.currency=$('#currencyInput').value;data.settings.onlinePaymentEnabled=$('#paymentToggle').checked;data.settings.schoolTransportEnabled=$('#schoolToggle').checked;BAP.setData(data);renderBookings();toast('تم حفظ الإعدادات');};
  $('#resetBtn').onclick=()=>{data=BAP.resetData();renderAll();toast('تمت استعادة بيانات المشروع الأصلية');};
  function renderAll(){renderBookings();renderServices();renderPackages();renderProducts();renderFaqs();loadContent();loadSettings();}
  renderAll();
})();
